name: Update README.md with terraform docs

on:
  push:
    branches:
      - master
      - main

jobs:
  documentation:
    name: Render terraform docs inside the README.md and push changes back to PR branch
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v2
      - name: Render terraform docs inside the README.md and push changes back to PR branch
        uses: terraform-docs/gh-actions@v0.11.0
        with:
          working-dir: .
          output-file: README.md
          output-method: inject
          git-push: "true"